name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release StreamDeckFreeAtHome
